apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-to-registry-task
spec:
  steps:
    - name: docker-push
      image: docker:20.10.7
      script: |
        docker push gcr.io/ford-435123/fordpoc:latest
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
