apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  triggers:
    - name: github-trigger
      binding:
        ref: github-triggerbinding
      template:
        ref: github-triggertemplate
