apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-triggerbinding
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.html_url)
    - name: git-revision
      value: $(body.head_commit.id)
