apiVersion: v1
kind: Service
metadata:
  name: tekton-eventlistener
  namespace: tekton-pipelines
spec:
  type: LoadBalancer
  selector:
    app: tekton-listener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
